# Numpy operations and boolean

In this particular notebook, i'll be doing mathematical functions & Boolean operations. Let's get started.

In [1]:
# import necessary libraries
import numpy as np

In [2]:
array = np.random.randint(20, size=(4, 5, 3))

array

array([[[13,  7, 15],
        [17,  3, 14],
        [12,  6,  4],
        [16, 18, 19],
        [17,  3, 11]],

       [[ 4,  2, 10],
        [ 2, 13,  4],
        [ 1, 12, 15],
        [ 6, 13,  2],
        [ 9,  8,  1]],

       [[ 1,  2,  2],
        [ 6, 17,  1],
        [18,  2,  0],
        [ 9,  5, 19],
        [ 8,  4, 18]],

       [[13, 16,  8],
        [19, 10,  7],
        [10, 15, 19],
        [ 8, 19,  7],
        [19, 15,  3]]])

In [3]:
array.size

60

In [4]:
array.shape

(4, 5, 3)

In [5]:
array.ndim

3

In [6]:
array.dtype

dtype('int32')

In [9]:
array2 = np.random.randint(20, size=(5, 10, 3))

array2

array([[[15, 10, 17],
        [ 8,  4,  4],
        [13, 11, 15],
        [ 8,  6,  2],
        [ 8, 14,  7],
        [16,  7,  8],
        [ 3,  6, 14],
        [ 3,  8,  7],
        [16, 19,  4],
        [ 1,  5, 13]],

       [[15, 19, 15],
        [16, 16, 17],
        [ 9, 15,  9],
        [ 2,  4, 18],
        [ 8, 10,  6],
        [ 2,  4,  2],
        [11, 11,  2],
        [ 5,  8,  2],
        [12,  1,  7],
        [ 4, 11,  6]],

       [[10, 10, 12],
        [16, 12, 15],
        [ 3,  7, 15],
        [16,  6,  3],
        [ 6, 11,  2],
        [ 1, 12, 15],
        [17, 13, 17],
        [12, 12,  6],
        [11, 10, 10],
        [14, 15,  9]],

       [[ 1, 12, 13],
        [12,  5, 11],
        [15,  4,  9],
        [10,  9, 10],
        [16, 19,  8],
        [11,  9,  8],
        [11, 11,  0],
        [ 4, 19, 19],
        [10,  4, 14],
        [ 6,  3, 18]],

       [[ 2, 19,  4],
        [11, 18, 19],
        [ 1,  3, 15],
        [ 4,  2,  3],
        [12, 13, 15],
  

In [10]:
array2.size

150

In [11]:
array2.shape

(5, 10, 3)

In [12]:
array2.ndim

3

In [13]:
# checking whether the realtions, boolean operations
ans = (array==array2)

ans

C:\Users\Miss Gloriah\AppData\Local\Temp\ipykernel_3268\2834137326.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  ans = (array==array2)


False

In [15]:
if (ans == True):
    print(array)
else:
    print(array2)

[[[15 10 17]
  [ 8  4  4]
  [13 11 15]
  [ 8  6  2]
  [ 8 14  7]
  [16  7  8]
  [ 3  6 14]
  [ 3  8  7]
  [16 19  4]
  [ 1  5 13]]

 [[15 19 15]
  [16 16 17]
  [ 9 15  9]
  [ 2  4 18]
  [ 8 10  6]
  [ 2  4  2]
  [11 11  2]
  [ 5  8  2]
  [12  1  7]
  [ 4 11  6]]

 [[10 10 12]
  [16 12 15]
  [ 3  7 15]
  [16  6  3]
  [ 6 11  2]
  [ 1 12 15]
  [17 13 17]
  [12 12  6]
  [11 10 10]
  [14 15  9]]

 [[ 1 12 13]
  [12  5 11]
  [15  4  9]
  [10  9 10]
  [16 19  8]
  [11  9  8]
  [11 11  0]
  [ 4 19 19]
  [10  4 14]
  [ 6  3 18]]

 [[ 2 19  4]
  [11 18 19]
  [ 1  3 15]
  [ 4  2  3]
  [12 13 15]
  [14  9 19]
  [17  6 19]
  [ 2  5 18]
  [14  0 13]
  [ 4 15 14]]]


In [16]:
array == array2

C:\Users\Miss Gloriah\AppData\Local\Temp\ipykernel_3268\3482704128.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  array == array2


False

In [17]:
array.sum()

577

In [18]:
array.mean()

9.616666666666667

In [19]:
array.max()

19

In [21]:
array.min()

0

In [22]:
len(array)

4

In [23]:
array2.sum()

1468

In [24]:
array2.max()

19

In [25]:
array2.min()

0

In [26]:
array2.mean()

9.786666666666667

In [28]:
# random np array with float\
arr = np.random.randint(15, size=(4,6,3))

arr

array([[[14,  6,  6],
        [ 0,  8,  9],
        [ 3, 14,  0],
        [ 5, 12,  0],
        [ 2,  3, 11],
        [13,  7,  9]],

       [[ 0,  9,  8],
        [ 8, 12, 11],
        [11, 13, 13],
        [11, 14, 14],
        [ 7,  1, 13],
        [ 4,  7,  0]],

       [[ 5,  6,  2],
        [ 5,  6,  2],
        [ 2, 13, 13],
        [ 4,  8, 12],
        [ 0,  3,  5],
        [ 1,  8,  6]],

       [[ 7, 13,  5],
        [10, 11,  5],
        [ 1,  2,  6],
        [ 1,  0, 10],
        [ 3,  8, 12],
        [11,  8, 14]]])