# Numpy Summary

In this particular excercise, I'm doing a final document of everything I did this week. Let's do this recap.

In [1]:
# imports
import numpy as np

In [2]:
#creating arrays
array = np.random.randint(20, size=6)

array

array([15,  9,  3,  0, 11, 13])

In [3]:
arr = np.random.randint(15, size=(3,5))

arr

array([[10,  7,  4,  4,  3],
       [ 5,  1, 14,  6,  6],
       [13, 14,  4, 13,  7]])

In [5]:
array2 = np.random.randint(10, size=(5, 10, 4))

array2

array([[[6, 9, 4, 4],
        [9, 5, 5, 5],
        [3, 8, 2, 3],
        [9, 5, 2, 4],
        [1, 9, 2, 1],
        [3, 0, 3, 4],
        [9, 6, 0, 8],
        [5, 7, 7, 6],
        [7, 0, 2, 5],
        [7, 8, 0, 2]],

       [[1, 7, 5, 0],
        [9, 8, 7, 8],
        [0, 2, 5, 6],
        [7, 0, 9, 6],
        [5, 4, 5, 9],
        [8, 6, 0, 3],
        [4, 5, 9, 9],
        [8, 5, 5, 9],
        [5, 8, 8, 8],
        [0, 1, 8, 3]],

       [[4, 2, 9, 7],
        [4, 6, 2, 5],
        [3, 1, 8, 7],
        [7, 0, 6, 3],
        [5, 2, 5, 5],
        [3, 2, 8, 4],
        [3, 9, 4, 2],
        [1, 3, 1, 1],
        [7, 6, 0, 2],
        [4, 6, 5, 2]],

       [[7, 1, 6, 0],
        [2, 2, 0, 8],
        [6, 8, 5, 4],
        [3, 2, 5, 8],
        [6, 5, 3, 5],
        [2, 7, 6, 1],
        [9, 7, 8, 0],
        [5, 9, 6, 2],
        [0, 1, 3, 1],
        [7, 6, 4, 2]],

       [[6, 3, 8, 3],
        [8, 2, 0, 4],
        [5, 9, 0, 9],
        [9, 0, 3, 0],
        [1, 1, 9, 2],
  

In [6]:
# Checking the properties
array.ndim

1

In [7]:
arr.ndim

2

In [8]:
array2.ndim

3

In [10]:
array.shape

(6,)

In [11]:
arr.shape

(3, 5)

In [12]:
array2.shape

(5, 10, 4)

In [13]:
array.size

6

In [14]:
arr.size

15

In [15]:
array2.size

200

In [16]:
len(array)

6

In [17]:
len(array2)

5

In [18]:
len(arr)

3

In [19]:
# Boolean operation
array == array2

C:\Users\Miss Gloriah\AppData\Local\Temp\ipykernel_18924\3202488325.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  array == array2


False

In [20]:
array2 == arr

C:\Users\Miss Gloriah\AppData\Local\Temp\ipykernel_18924\2313331500.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  array2 == arr


False

In [21]:
arr == array

C:\Users\Miss Gloriah\AppData\Local\Temp\ipykernel_18924\3705118190.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  arr == array


False

In [22]:
# Boolean Function
if (array == arr):
    print(array)
else:
    print(arr)

[[10  7  4  4  3]
 [ 5  1 14  6  6]
 [13 14  4 13  7]]


C:\Users\Miss Gloriah\AppData\Local\Temp\ipykernel_18924\939055228.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if (array == arr):


In [23]:
# Mathematical functions
array.sum()

51

In [24]:
arr.sum()

111

In [25]:
array2.sum()

922

In [26]:
arr.min()

1

In [27]:
array2.min()

0

In [28]:
array.min()

0

In [29]:
array.mean()

8.5

In [30]:
arr.mean()

7.4

In [31]:
array2.mean()

4.61

In [32]:
array2.std()

2.849192868164596

In [33]:
arr.std()

4.17612260356422

In [34]:
array.std()

5.346338310781813

In [35]:
#My lessons are done