# Numpy Array Creation

In this notebook, I will be doing the numpy array and datasets creations.

Since numpy uses N-arrays, I'll focus on understanding how to create the arrays and perform other functions in the arrays.
My goals for this excercise, is to :-
 -Understand Numpy
 -Create arrays
 -Perform some array functions

In [1]:
#Importing the needed library
import numpy as np

In [2]:
#creating a 1D array
array_1 = np.array([[1,2,4]])

array_1

array([[1, 2, 4]])

In [3]:
# exploring the array
array_1.shape

(1, 3)

In [4]:
array_1.dtype

dtype('int32')

In [5]:
# Creating a placeholder array
array_2 = np.ones((1,6))

In [6]:
array_2

array([[1., 1., 1., 1., 1., 1.]])

In [7]:
array_2.shape

(1, 6)

In [8]:
array_2.dtype

dtype('float64')

In [9]:
array_2.ndim

2

In [10]:
array_2.size

6

In [11]:
len(array_2)

1

In [12]:
# Generating a random array 
arr = np.arange(20)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
arr.shape

(20,)

In [15]:
arr.ndim

1

In [16]:
arr.size

20

In [19]:
arr2 = np.random.randint(60, size=(2,3))

In [20]:
arr2

array([[27, 16, 18],
       [33,  2,  7]])

In [21]:
arr3 = np.eye(3)

In [22]:
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])