# Numpy Part 2

In [1]:
# import necessary Library
import numpy as np

In [2]:
arr = np.array([3,4,5,6,8,9,1])

In [3]:
arr

array([3, 4, 5, 6, 8, 9, 1])

In [4]:
arr2=np.array([1,4,5,6,3,7,7])

In [5]:
arr2

array([1, 4, 5, 6, 3, 7, 7])

In [6]:
array = arr+arr2

In [7]:
array

array([ 4,  8, 10, 12, 11, 16,  8])

In [12]:
arr3 = np.array([1,4,5,7,8,9,1,3])

In [14]:
arr3.reshape(4,2)

array([[1, 4],
       [5, 7],
       [8, 9],
       [1, 3]])

In [16]:
arr3.shape

(8,)

In [17]:
arr3.size

8

In [18]:
arr3.dtype

dtype('int32')

In [19]:
arr3.ndim

1

In [20]:
# Let's create a two-dimentional array now
nd_arr = np.array([[1,2,3,4], [4,7,6,8]])

In [21]:
nd_arr

array([[1, 2, 3, 4],
       [4, 7, 6, 8]])

In [22]:
nd_arr.ndim

2

In [23]:
nd_arr.shape

(2, 4)

In [24]:
nd_arr.size

8

In [27]:
len(nd_arr)

2

In [28]:
nd_arr[4:, ]

array([], shape=(0, 4), dtype=int32)

In [30]:
nd_arr[:, 3]

array([4, 8])

In [33]:
nd_arr[2:]

array([], shape=(0, 4), dtype=int32)

In [35]:
# generating random arrays
array = np.random.randint(16, size=4)

In [36]:
array

array([ 7,  2,  9, 11])

In [37]:
array.reshape(2,2)

array([[ 7,  2],
       [ 9, 11]])

In [39]:
array1 = np.random.randint(25, size=10)

In [40]:
array1

array([13, 15, 22, 14, 22, 16,  6,  5,  1, 13])

In [41]:
array1.reshape(2,5)

array([[13, 15, 22, 14, 22],
       [16,  6,  5,  1, 13]])