# Building 3D arrays and Understanding its properties

In this part of the process, I will be building 3D arrays and also perform some property evaluation while at it. 

In [1]:
# Import necessary library
import numpy as np

In [2]:
array = np.array([[1,2,3,4,5], [1,5,7,8,4], [1,6,7,8,3]])

array

array([[1, 2, 3, 4, 5],
       [1, 5, 7, 8, 4],
       [1, 6, 7, 8, 3]])

In [3]:
array.shape

(3, 5)

In [4]:
array.size

15

In [5]:
array.ndim

2

In [6]:
# creating a 3D array
array3 = np.array([[[1,4,5,6], [1,6,7,9], [1,6,4,5], [1,8,7,4]]])
array3

array([[[1, 4, 5, 6],
        [1, 6, 7, 9],
        [1, 6, 4, 5],
        [1, 8, 7, 4]]])

In [7]:
array3.size

16

In [9]:
array3.shape

(1, 4, 4)

In [10]:
array3.ndim

3

In [11]:
len(array3)

1

In [12]:
# using random integers to create an array
arr = np.random.randint(70, size=(4,70,3))

In [13]:
arr

array([[[49, 31, 20],
        [23, 54, 40],
        [ 5, 61, 59],
        [55, 35, 53],
        [58,  7, 42],
        [30, 11, 54],
        [22, 32, 24],
        [53,  1, 66],
        [42, 40, 10],
        [20, 68, 27],
        [28, 68, 46],
        [16, 48,  7],
        [26, 50, 36],
        [61, 17, 31],
        [14, 57, 40],
        [59, 25,  2],
        [20, 29, 10],
        [14, 20, 32],
        [45, 38, 38],
        [36, 22, 16],
        [27,  7, 63],
        [55, 23, 47],
        [45, 16, 27],
        [66, 65,  0],
        [25, 49, 34],
        [22, 47, 66],
        [40, 65, 60],
        [38, 24, 46],
        [67, 46, 65],
        [33, 37, 17],
        [67, 16, 11],
        [10, 11, 45],
        [13, 59, 27],
        [39, 23, 37],
        [15, 12, 44],
        [57, 60, 54],
        [12, 40, 42],
        [57, 28, 35],
        [20,  9, 35],
        [29, 17, 63],
        [53, 56, 33],
        [13, 35, 12],
        [25, 69,  8],
        [42, 25,  7],
        [53,  5, 24],
        [2

In [14]:
arr.size

840

In [15]:
arr.shape

(4, 70, 3)

In [16]:
arr1 = np.random.randint(45, size=(4, 20, 3))

In [17]:
arr1

array([[[ 3, 40, 39],
        [40, 20, 34],
        [32, 24, 36],
        [32, 39, 35],
        [20, 32,  9],
        [35, 29, 34],
        [ 9, 21, 18],
        [17,  9, 39],
        [ 9, 18, 20],
        [ 4, 31,  6],
        [19, 18, 10],
        [38, 43, 18],
        [25, 15, 17],
        [ 6, 23,  5],
        [19, 31, 11],
        [30, 29, 37],
        [19, 35,  1],
        [32,  3, 24],
        [38,  7,  0],
        [13, 38, 18]],

       [[39,  6, 19],
        [21, 32, 10],
        [24, 15, 16],
        [ 4,  1, 39],
        [31,  7,  3],
        [16,  6, 13],
        [10, 29, 28],
        [11, 44, 17],
        [23, 27,  8],
        [25,  5, 41],
        [ 8, 10, 30],
        [22, 25, 39],
        [ 7, 33, 25],
        [40, 43, 27],
        [41, 16, 42],
        [17,  4, 35],
        [ 0, 32, 14],
        [40, 33, 21],
        [39, 11, 14],
        [35,  9, 41]],

       [[12, 32, 27],
        [ 3, 16, 23],
        [20,  6, 21],
        [36, 40, 36],
        [20, 33,  0],
      

In [18]:
arr1.ndim

3

In [19]:
arr1.dtype

dtype('int32')

In [20]:
# in this part i will create a final 3D array each of 15 items and of random integers
array_1 = np.random.randint(100, size=(4, 15, 5))

In [21]:
array_1

array([[[71, 45, 53, 91,  0],
        [84, 64, 32, 22, 17],
        [59,  2, 18, 46, 47],
        [76, 90, 39,  7, 39],
        [88, 83, 48, 75, 32],
        [ 3, 54,  0, 12, 20],
        [33, 53, 75, 27, 41],
        [96, 24, 45, 59, 97],
        [21, 37, 44, 28, 16],
        [95, 77, 77, 47, 30],
        [12, 30, 63, 30, 72],
        [42, 30, 60, 98, 88],
        [39, 85,  6, 59,  1],
        [18, 49, 70, 11, 48],
        [94,  4, 15, 73, 92]],

       [[12, 62, 36,  1, 41],
        [71, 57, 40, 96, 98],
        [61, 20, 47, 82,  7],
        [53, 89, 64, 81, 20],
        [62, 31, 44, 84, 64],
        [22, 70, 16, 26, 80],
        [71, 43, 42, 40, 34],
        [26, 62, 88, 92, 86],
        [19, 46,  5, 98, 57],
        [48,  7, 93, 70, 28],
        [88, 19, 85, 28, 57],
        [68, 70, 36, 73, 35],
        [51,  8, 88, 59, 49],
        [12, 19, 74, 70, 31],
        [11, 93, 62, 52, 13]],

       [[83, 12,  1, 18, 23],
        [63, 97, 13, 55, 46],
        [86, 75, 39, 12, 73],
      

I have completed my work for the day